---
    - name: Install Requirements
      apt: name="{{ item }}" state=absent
      loop:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb
        - python-apt
      become: yes